version: '3'
services:
  web:
    container_name: vi_school_web
    image: nginx:latest
    volumes:
      - .:/code:cached
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 1580:80
    links:
      - php
  php:
    container_name: vi_school_php
    build: .docker/php
    volumes:
      - .:/code:cached
      - .docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      TIMEZONE: Europe/Moscow
    links:
      - mysql
    working_dir: /code
  mysql:
    container_name: vi_school_mysql
    image: mysql:5.7
    ports:
      - "15006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vi_school_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
